### ISSUE TITLE
Emacs theme

### ISSUE THREAD

**Issue by brihadeesh** [AlessandroYorba/Breve#2]
Hi I'm curious as to whether this theme has been ported to Emacs. Else I could try and do so myself albeit somewhat slowly :)

**Comment by AlessandroYorba** [comment]
@brihadeesh go for it! You're the first to ask so I'm not aware of any other takers. I based it off the theme Espresso from the text editor here: https://www.espressoapp.com. There's still a lot of work to be done on Breve. I'll spend this week looking at it some more.

**Comment by brihadeesh** [comment]
Great! Will get back here once I've made some progress.

**Comment by brihadeesh** [comment]
Hi @AlessandroYorba , I came across a theme called [`expresso`](https://github.com/dgutov/espresso-theme) which resembles Breve and is also inspired from the expresso app!
